version: "3"

services:
  # Backend Service
  appointmentApp:
    image: wisekingdavid/appoitment-app:0.1
    container_name: appointment-server
    ports:
      - "8080:8080"
    environment:
      - SW_AGENT_NAME:appointment-app
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES:host.docker.internal:11800

  oap:
    image: apache/skywalking-oap-server:9.1.0
    container_name: oap

    restart: on-failure:5
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: h2
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
    depends_on:
      - appointmentApp

  ui:
    image: apache/skywalking-ui:9.1.0
    container_name: ui
    links:
      - oap
    ports:
      - "8088:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    depends_on:
      - oap
